language:
  - cpp

os:
  - linux
#  - osx

compiler:
  - clang
#  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

sudo:
  - false

install:
  # Info about OS
  - uname -a
