# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

sudo: required
dist: trusty
language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - openssl
            - libssl-dev
            - libcurl4-openssl-dev
            - cmake
            - cmake-data
            - gcc-4.9
            - g++-4.9
            - gfortran-4.9
            - clang-3.7
            #    - valgrind

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          if [[ "$CXX" == "g++" ]]; then
              export CXX="g++-4.9"
              export CC="gcc-4.9"
              export FC="gfortran-4.9"
          elif [[ "$CXX" == "clang" ]]; then
              export FC="gfortran"
          fi
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          export FC="gfortran"
      endif

install:
    - echo ${PATH}
    - echo ${CC}
    - echo ${CXX}
    - echo ${FC}

before_script:
    - cmake --version
    - curl --version
    - ${CC} --version
    - ${CXX} --version
    - ${FC} --version

script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
    - ctest
